CREATE TABLE ENDERECO (
      ID INT AUTO_INCREMENT PRIMARY KEY,
      RUA VARCHAR(100),
      NUMERO VARCHAR(6),
      CEP VARCHAR(9),
      CIDADE VARCHAR(100),
      ESTADO VARCHAR(50),
      PAIS VARCHAR(20),
      ATIVO BOOLEAN,
      DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      DATA_MODIFICACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
