CREATE TABLE EMPRESA (
     ID INT AUTO_INCREMENT PRIMARY KEY,
     NOME VARCHAR(100),
     RAZAO_SOCIAL VARCHAR(250),
     CNPJ VARCHAR(18),
     TELEFONE VARCHAR(20),
     ENDERECO_FK INT,
     ATIVO BOOLEAN,
     DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     DATA_MODIFICACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     FOREIGN KEY (ENDERECO_FK) REFERENCES ENDERECO(ID)
);