CREATE TABLE COLABORADOR (
     ID INT AUTO_INCREMENT PRIMARY KEY,
     NOME VARCHAR(250),
     CPF VARCHAR(14),
     TELEFONE VARCHAR(20),
     EMAIL VARCHAR(100),
     ENDERECO_FK INT,
     EMPRESA_FK INT,
     PROFISSAO VARCHAR(100),
     SALARIO DECIMAL(10, 2),
     CARGO VARCHAR(100),
     DATA_CONTRATACAO DATE,
     DATA_DESLIGAMENTO DATE,
     ATIVO BOOLEAN,
     DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     DATA_MODIFICACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     FOREIGN KEY (ENDERECO_FK) REFERENCES ENDERECO(ID),
     FOREIGN KEY (EMPRESA_FK) REFERENCES EMPRESA(ID)
);
